# Create a new task
POST http://localhost:3000/api/tasks/create HTTP/1.1
Content-Type: application/json

{
  "userId": "1",
  "title": "name",
  "description": "sdasdfdasflkjf",
  "category": [3, 5],
  "price": 100,
  "tillDate": "2023-10-22",
  "city": "Moscow",
  "picture": " ",
  "address": " Arbat 1",
  "tags": "new"
}

###


# Get task by ID
GET http://localhost:3000/api/tasks/12 HTTP/1.1

###


# Delete task by ID
DELETE http://localhost:3000/api/tasks/8 HTTP/1.1

###


# Update a task
PATCH  http://localhost:3000/api/tasks/21 HTTP/1.1
Content-Type: application/json

{
  "title": "new name"
}

###

# Get all posts and filtres
GET http://localhost:3000/api/tasks?sortDirection=desc&category=1&limit=5&page=1 HTTP/1.1

###