# Upload some file
POST http://localhost:3000/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.txt"

< /Users/dmitriybocenkov/Projects/2101165-taskforce-4/project/apps/uploader/uploads/test.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Get file by ID
GET http://localhost:3000/api/files/64ec3e75ebfcbdc3cf8d49dc HTTP/1.1

###